Start -> "export GOOGLE_APPLICATION_CREDENTIALS=<JsonSAKeyPath>" -> terraform init -> terraform apply -auto-approve
terraform apply -auto-approve -> terraform apply -auto-approve -var='enable_security_policy=true': Untuk mengaktifkan Cloud Armor
terraform apply -auto-approve -var='enable_security_policy=true' -> End

Start.shape: oval
End.shape: oval
